"""add notes and finalize todo backend

Revision ID: 7c0e77970cc8
Revises: 737573da871e
Create Date: 2026-04-18 11:09:52.073528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0e77970cc8'
down_revision = '737573da871e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
